language: ruby

rvm:
  - 2.2.6

cache: bundler

bundler_args: --without production

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
  - bundle exec rails db:seed
